# Generated by Django 3.1.3 on 2020-11-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_id',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='postal_code',
            field=models.CharField(max_length=32),
        ),
    ]
