# Generated by Django 3.1.3 on 2020-11-07 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.CharField(max_length=32)),
                ('caption', models.TextField()),
                ('label', models.CharField(max_length=32)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='business.business')),
            ],
        ),
    ]
