# Generated by Django 3.1.3 on 2020-11-07 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='users',
        ),
    ]
