# Generated by Django 3.1.3 on 2020-11-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20201107_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='attributes',
            field=models.JSONField(null=True),
        ),
    ]
