# Generated by Django 3.1.3 on 2020-11-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_remove_room_users'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userinroom',
            constraint=models.UniqueConstraint(fields=('room', 'user'), name='unique_room_user'),
        ),
    ]
