# Generated by Django 3.1.3 on 2020-11-07 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20201107_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_business_chosen', models.BooleanField(null=True)),
                ('first_business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='business.business')),
                ('second_business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='business.business')),
                ('user_in_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='business.userinroom')),
            ],
        ),
    ]
