# Generated by Django 3.1.3 on 2020-11-07 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinroom',
            name='status',
        ),
    ]
